
package CiscoUC::Perfmon::9_1::Elements::perfmonOpenSessionResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' }

__PACKAGE__->__set_name('perfmonOpenSessionResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %perfmonOpenSessionReturn_of :ATTR(:get<perfmonOpenSessionReturn>);

__PACKAGE__->_factory(
    [ qw(        perfmonOpenSessionReturn

    ) ],
    {
        'perfmonOpenSessionReturn' => \%perfmonOpenSessionReturn_of,
    },
    {
        'perfmonOpenSessionReturn' => 'CiscoUC::Perfmon::9_1::Types::SessionHandleType',
    },
    {

        'perfmonOpenSessionReturn' => 'perfmonOpenSessionReturn',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CiscoUC::Perfmon::9_1::Elements::perfmonOpenSessionResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
perfmonOpenSessionResponse from the namespace http://schemas.cisco.com/ast/soap.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * perfmonOpenSessionReturn

 $element->set_perfmonOpenSessionReturn($data);
 $element->get_perfmonOpenSessionReturn();





=back


=head1 METHODS

=head2 new

 my $element = CiscoUC::Perfmon::9_1::Elements::perfmonOpenSessionResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   perfmonOpenSessionReturn =>  { value => $some_value },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

