package MyTypes::ServiceInformation;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ServiceName_of :ATTR(:get<ServiceName>);
my %ServiceStatus_of :ATTR(:get<ServiceStatus>);
my %ReasonCode_of :ATTR(:get<ReasonCode>);
my %ReasonCodeString_of :ATTR(:get<ReasonCodeString>);
my %StartTime_of :ATTR(:get<StartTime>);
my %UpTime_of :ATTR(:get<UpTime>);

__PACKAGE__->_factory(
    [ qw(        ServiceName
        ServiceStatus
        ReasonCode
        ReasonCodeString
        StartTime
        UpTime

    ) ],
    {
        'ServiceName' => \%ServiceName_of,
        'ServiceStatus' => \%ServiceStatus_of,
        'ReasonCode' => \%ReasonCode_of,
        'ReasonCodeString' => \%ReasonCodeString_of,
        'StartTime' => \%StartTime_of,
        'UpTime' => \%UpTime_of,
    },
    {
        'ServiceName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ServiceStatus' => 'MyTypes::ServiceStatus',
        'ReasonCode' => 'SOAP::WSDL::XSD::Typelib::Builtin::integer',
        'ReasonCodeString' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'StartTime' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'UpTime' => 'SOAP::WSDL::XSD::Typelib::Builtin::integer',
    },
    {

        'ServiceName' => 'ServiceName',
        'ServiceStatus' => 'ServiceStatus',
        'ReasonCode' => 'ReasonCode',
        'ReasonCodeString' => 'ReasonCodeString',
        'StartTime' => 'StartTime',
        'UpTime' => 'UpTime',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

MyTypes::ServiceInformation

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ServiceInformation from the namespace http://schemas.cisco.com/ast/soap.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ServiceName (min/maxOccurs: 1/1)


=item * ServiceStatus (min/maxOccurs: 1/1)


=item * ReasonCode (min/maxOccurs: 1/1)


=item * ReasonCodeString (min/maxOccurs: 1/1)


=item * StartTime (min/maxOccurs: 1/1)


=item * UpTime (min/maxOccurs: 1/1)




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # MyTypes::ServiceInformation
   ServiceName =>  $some_value, # string
   ServiceStatus => $some_value, # ServiceStatus
   ReasonCode =>  $some_value, # integer
   ReasonCodeString =>  $some_value, # string
   StartTime =>  $some_value, # string
   UpTime =>  $some_value, # integer
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

