
package CiscoUC::Log::10_0::Elements::selectLogFilesResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' }

__PACKAGE__->__set_name('selectLogFilesResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ResultSet_of :ATTR(:get<ResultSet>);

__PACKAGE__->_factory(
    [ qw(        ResultSet

    ) ],
    {
        'ResultSet' => \%ResultSet_of,
    },
    {
        'ResultSet' => 'CiscoUC::Log::10_0::Types::ResultSet',
    },
    {

        'ResultSet' => 'ResultSet',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CiscoUC::Log::10_0::Elements::selectLogFilesResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
selectLogFilesResponse from the namespace http://schemas.cisco.com/ast/soap.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ResultSet

 $element->set_ResultSet($data);
 $element->get_ResultSet();





=back


=head1 METHODS

=head2 new

 my $element = CiscoUC::Log::10_0::Elements::selectLogFilesResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   ResultSet =>  { # CiscoUC::Log::10_0::Types::ResultSet
     SchemaFileSelectionResult =>  { # CiscoUC::Log::10_0::Types::SchemaFileSelectionResult
       Node =>  { # CiscoUC::Log::10_0::Types::Node
         name =>  $some_value, # string
         ServiceList =>  { # CiscoUC::Log::10_0::Types::ArrayOfServiceLogs
           ServiceLogs =>  { # CiscoUC::Log::10_0::Types::ServiceLogs
             name =>  $some_value, # string
             SetOfFiles =>  { # CiscoUC::Log::10_0::Types::ArrayOfFile
               File =>  { # CiscoUC::Log::10_0::Types::File
                 name =>  $some_value, # string
                 absolutepath =>  $some_value, # string
                 filesize =>  $some_value, # string
                 modifiedDate =>  $some_value, # string
               },
             },
           },
         },
       },
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

