
package CiscoUC::Perfmon::10_0::Elements::perfmonListCounterResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' }

__PACKAGE__->__set_name('perfmonListCounterResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %perfmonListCounterReturn_of :ATTR(:get<perfmonListCounterReturn>);

__PACKAGE__->_factory(
    [ qw(        perfmonListCounterReturn

    ) ],
    {
        'perfmonListCounterReturn' => \%perfmonListCounterReturn_of,
    },
    {
        'perfmonListCounterReturn' => 'CiscoUC::Perfmon::10_0::Types::ObjectInfoType',
    },
    {

        'perfmonListCounterReturn' => 'perfmonListCounterReturn',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CiscoUC::Perfmon::10_0::Elements::perfmonListCounterResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
perfmonListCounterResponse from the namespace http://schemas.cisco.com/ast/soap.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * perfmonListCounterReturn

 $element->set_perfmonListCounterReturn($data);
 $element->get_perfmonListCounterReturn();





=back


=head1 METHODS

=head2 new

 my $element = CiscoUC::Perfmon::10_0::Elements::perfmonListCounterResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   perfmonListCounterReturn =>  { # CiscoUC::Perfmon::10_0::Types::ObjectInfoType
     Name =>  { value => $some_value },
     MultiInstance =>  $some_value, # boolean
     ArrayOfCounter =>  { # CiscoUC::Perfmon::10_0::Types::ArrayOfCounterType
       item =>  { # CiscoUC::Perfmon::10_0::Types::CounterType
         Name =>  { value => $some_value },
       },
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

