
package CiscoUC::RIS::10_5::Typemaps::RISService;
use strict;
use warnings;

our $typemap_1 = {
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/CtiDevice/DeviceStatusReason' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/LoginUserId' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice' => 'CiscoUC::RIS::10_5::Types::CmDevice',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/AppStatusReason' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCtiItem/CtiSelectionCriteria/DirNumbers/item' => 'CiscoUC::RIS::10_5::Types::SelectDirNumber',
               'selectCmDevice/CmSelectionCriteria/DeviceClass' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP' => 'CiscoUC::RIS::10_5::Types::SelectCmDeviceResultSIP',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/H323Trunk/ActiveGk' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/AppStatus' => 'CiscoUC::RIS::10_5::Types::CtiStatus',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/H323Trunk/RasAddr' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'getServerInfoResponse/ServerInformation/java-runtime-version' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/TimeStamp' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices' => 'CiscoUC::RIS::10_5::Types::ArrayOfCmDevice',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/Httpd' => 'CiscoUC::RIS::10_5::Types::CmDevHttpd',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/TotalDevicesFound' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/RegistrationAttempts' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/CtiDevice/DeviceName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/H323Trunk/RemoteCmServer1' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/PerfMonObject' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/Name' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'executeCCMSQLStatement/GetColumns' => 'CiscoUC::RIS::10_5::Types::ColumnType',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult' => 'CiscoUC::RIS::10_5::Types::SelectCmDeviceResult',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/Name' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/CtiDevice/DeviceStatus' => 'CiscoUC::RIS::10_5::Types::CtiStatus',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/TimeStamp' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/BoxProduct' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceSIP/CmSelectionCriteriaSIP/SelectItems/item/Item' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/H323Trunk/AltGkList' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDevice/CmSelectionCriteria/SelectItems' => 'CiscoUC::RIS::10_5::Types::ArrayOfSelectItem',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/IsCtiControllable' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/TotalItemsFound' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/NoChange' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
               'getServerInfoResponse' => 'CiscoUC::RIS::10_5::Elements::getServerInfoResponse',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/IpAddress' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItem/CtiSelectionCriteria/MaxReturnedItems' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/H323Trunk/TechPrefix' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/LoginUserId' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItem/CtiSelectionCriteria/DevNames/SelectDevName' => 'CiscoUC::RIS::10_5::Types::SelectDevName',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/ReturnCode' => 'CiscoUC::RIS::10_5::Types::RisReturnCode',
               'selectCmDeviceResponse/selectCmDeviceResponse' => 'CiscoUC::RIS::10_5::Types::selectCmDeviceReturn',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/H323Trunk' => 'CiscoUC::RIS::10_5::Types::H323Trunk',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/DeviceClass' => 'CiscoUC::RIS::10_5::Types::DeviceClass',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/H323Trunk/Zone' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'executeCCMSQLStatementResponse/ExecuteSQLOutputData/Value' => 'CiscoUC::RIS::10_5::Types::ColumnVType',
               'selectCmDevice/StateInfo' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems' => 'CiscoUC::RIS::10_5::Types::ArrayOfCtiItem',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/H323Trunk/ConfigName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItem/CtiSelectionCriteria/Status' => 'CiscoUC::RIS::10_5::Types::CtiStatus',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/Name' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItem/CtiSelectionCriteria/SelectAppBy' => 'CiscoUC::RIS::10_5::Types::CtiSelectAppBy',
               'selectCtiItemResponse/selectCtiItemReturn' => 'CiscoUC::RIS::10_5::Types::selectCtiItemReturn',
               'selectCmDeviceSIPResponse' => 'CiscoUC::RIS::10_5::Elements::selectCmDeviceSIPResponse',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/AppId' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/IsCtiControllable' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
               'executeCCMSQLStatement/ExecuteSQLInputData' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/LinesStatus/item' => 'CiscoUC::RIS::10_5::Types::CmDevSingleLineStatus',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/H323Trunk/ActiveGk' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'executeCCMSQLStatementResponse' => 'CiscoUC::RIS::10_5::Elements::executeCCMSQLStatementResponse',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/H323Trunk/TechPrefix' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItemResponse/selectCtiItemReturn/StateInfo' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItem/CtiSelectionCriteria/AppItems/SelectAppItem/AppItem' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDevice' => 'CiscoUC::RIS::10_5::Elements::selectCmDevice',
               'selectCtiItem/CtiSelectionCriteria' => 'CiscoUC::RIS::10_5::Types::CtiSelectionCriteria',
               'selectCmDeviceSIP/CmSelectionCriteriaSIP/Status' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIP/StateInfo' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/AppTimeStamp' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/DChannel' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/CtiLine/LineStatus' => 'CiscoUC::RIS::10_5::Types::CtiStatus',
               'getServerInfoResponse/ServerInformation/java-vm-vendor' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'getServerInfoResponse/ServerInformation/os-name' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/Product' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCtiItem/StateInfo' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDevice/CmSelectionCriteria/Status' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/Status' => 'CiscoUC::RIS::10_5::Types::CmDevRegStat',
               'selectCmDeviceSIP' => 'CiscoUC::RIS::10_5::Elements::selectCmDeviceSIP',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/CtiDevice/DeviceTimeStamp' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/H323Trunk/RemoteCmServer2' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode' => 'CiscoUC::RIS::10_5::Types::CmNode',
               'selectCtiItem/CtiSelectionCriteria/DevNames' => 'CiscoUC::RIS::10_5::Types::ArrayOfSelectDevName',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/CtiLine/DirNumber' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/DeviceClass' => 'CiscoUC::RIS::10_5::Types::DeviceClass',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/H323Trunk/RemoteCmServer1' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'Fault' => 'SOAP::WSDL::SOAP::Typelib::Fault11',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/NoChange' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
               'selectCmDevice/CmSelectionCriteria/SelectBy' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceResponse/selectCmDeviceResponse/StateInfo' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'Fault/faultactor' => 'SOAP::WSDL::XSD::Typelib::Builtin::token',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/H323Trunk/CallSignalAddr' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/H323Trunk/Zone' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIP/CmSelectionCriteriaSIP/MaxReturnedDevices' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceSIP/CmSelectionCriteriaSIP/DeviceClass' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/Httpd' => 'CiscoUC::RIS::10_5::Types::CmDevHttpd',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/Status' => 'CiscoUC::RIS::10_5::Types::CmDevRegStat',
               'selectCmDeviceSIP/CmSelectionCriteriaSIP/SelectItems/item' => 'CiscoUC::RIS::10_5::Types::SelectItem',
               'selectCmDeviceSIP/CmSelectionCriteriaSIP/Model' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/Name' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/H323Trunk/RasAddr' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'getServerInfoResponse/ServerInformation/call-manager-version' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIP/CmSelectionCriteriaSIP' => 'CiscoUC::RIS::10_5::Types::CmSelectionCriteriaSIP',
               'Fault/faultcode' => 'SOAP::WSDL::XSD::Typelib::Builtin::anyURI',
               'selectCtiItem/CtiSelectionCriteria/DevNames/SelectDevName/DevName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDevice/CmSelectionCriteria/Model' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes' => 'CiscoUC::RIS::10_5::Types::CtiNode',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes' => 'CiscoUC::RIS::10_5::Types::ArrayOfCmNodeSIP',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/LinesStatus' => 'CiscoUC::RIS::10_5::Types::ArrayOfCmDevSingleLineStatus',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/H323Trunk/RemoteCmServer3' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'getServerInfoResponse/ServerInformation/os-arch' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/PerfMonObject' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/UserId' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'getServerInfo' => 'CiscoUC::RIS::10_5::Elements::getServerInfo',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/ReturnCode' => 'CiscoUC::RIS::10_5::Types::RisReturnCode',
               'selectCmDevice/CmSelectionCriteria/SelectItems/item/Item' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceResponse' => 'CiscoUC::RIS::10_5::Elements::selectCmDeviceResponse',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices' => 'CiscoUC::RIS::10_5::Types::ArrayOfCmDeviceSIP',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/ReturnCode' => 'CiscoUC::RIS::10_5::Types::RisReturnCode',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item' => 'CiscoUC::RIS::10_5::Types::CmDeviceSIP',
               'selectCtiItem/CtiSelectionCriteria/DirNumbers/item/DirNumber' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDevice/CmSelectionCriteria/SelectItems/item' => 'CiscoUC::RIS::10_5::Types::SelectItem',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/CtiLine' => 'CiscoUC::RIS::10_5::Types::CtiLine',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/H323Trunk/CallSignalAddr' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItem' => 'CiscoUC::RIS::10_5::Elements::selectCtiItem',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/CtiDevice/AppControlsMedia' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/AppIpAddr' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/Model' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'executeCCMSQLStatement/GetColumns/ColumnName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/Model' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDevice/CmSelectionCriteria/NodeName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/Product' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCtiItemResponse' => 'CiscoUC::RIS::10_5::Elements::selectCtiItemResponse',
               'Fault/faultstring' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/Name' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes' => 'CiscoUC::RIS::10_5::Types::ArrayOfCmNode',
               'selectCtiItem/CtiSelectionCriteria/NodeName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes' => 'CiscoUC::RIS::10_5::Types::ArrayOfCtiNode',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/H323Trunk/ConfigName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'Fault/detail' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/H323Trunk/RemoteCmServer2' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/StatusReason' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP' => 'CiscoUC::RIS::10_5::Types::CmNodeSIP',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/DirNumber' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDevice/CmSelectionCriteria/MaxReturnedDevices' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/StatusReason' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceSIP/CmSelectionCriteriaSIP/NodeName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'getServerInfoResponse/ServerInformation/Active_Versions' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/CtiDevice' => 'CiscoUC::RIS::10_5::Types::CtiDevice',
               'getServerInfoResponse/ServerInformation/os-version' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIP/CmSelectionCriteriaSIP/SelectBy' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIP/CmSelectionCriteriaSIP/Protocol' => 'CiscoUC::RIS::10_5::Types::ProtocolType',
               'selectCtiItem/CtiSelectionCriteria/CtiMgrClass' => 'CiscoUC::RIS::10_5::Types::CtiMgrClass',
               'executeCCMSQLStatement' => 'CiscoUC::RIS::10_5::Elements::executeCCMSQLStatement',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/Protocol' => 'CiscoUC::RIS::10_5::Types::ProtocolType',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/IpAddress' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/TotalDevicesFound' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'getServerInfo/Hosts' => 'CiscoUC::RIS::10_5::Types::Hosts',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/LinesStatus/item/Status' => 'CiscoUC::RIS::10_5::Types::CmSingleLineStatus',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/Description' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'getServerInfoResponse/ServerInformation/HostName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItem/CtiSelectionCriteria/DirNumbers' => 'CiscoUC::RIS::10_5::Types::ArrayOfSelectDirNumber',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/StateInfo' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/RegistrationAttempts' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/BoxProduct' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCtiItem/CtiSelectionCriteria/AppItems' => 'CiscoUC::RIS::10_5::Types::ArrayOfSelectAppItem',
               'getServerInfoResponse/ServerInformation/In_Active_Versions' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/DirNumber' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/H323Trunk/AltGkList' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDeviceSIP/CmSelectionCriteriaSIP/SelectItems' => 'CiscoUC::RIS::10_5::Types::ArrayOfSelectItem',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/Description' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/CtiLine/LineTimeStamp' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCtiItem/CtiSelectionCriteria/AppItems/SelectAppItem' => 'CiscoUC::RIS::10_5::Types::SelectAppItem',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/LinesStatus/item/DirectoryNumber' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCmDevice/CmSelectionCriteria' => 'CiscoUC::RIS::10_5::Types::CmSelectionCriteria',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/H323Trunk/RemoteCmServer3' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'getServerInfoResponse/ServerInformation' => 'CiscoUC::RIS::10_5::Types::ServerInformation',
               'selectCmDeviceResponse/selectCmDeviceResponse/SelectCmDeviceResult/CmNodes/CmNode/CmDevices/CmDevice/DChannel' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/H323Trunk' => 'CiscoUC::RIS::10_5::Types::H323Trunk',
               'executeCCMSQLStatementResponse/ExecuteSQLOutputData' => 'CiscoUC::RIS::10_5::Types::ColumnValueType',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse' => 'CiscoUC::RIS::10_5::Types::selectCmDeviceSIPReturn',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult' => 'CiscoUC::RIS::10_5::Types::SelectCtiItemResult',
               'selectCmDeviceSIPResponse/selectCmDeviceSIPResponse/SelectCmDeviceResultSIP/CmNodes/CmNodeSIP/CmDevices/item/NumOfLines' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'executeCCMSQLStatementResponse/ExecuteSQLOutputData/Name' => 'CiscoUC::RIS::10_5::Types::ColumnNType',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems' => 'CiscoUC::RIS::10_5::Types::CtiItem',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/CtiItems/CtiItems/CtiLine/LineStatusReason' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
               'getServerInfo/Hosts/Name' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
               'selectCtiItemResponse/selectCtiItemReturn/SelectCtiItemResult/CtiNodes/CtiNodes/NoChange' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean'
             };
;

sub get_class {
  my $name = join '/', @{ $_[1] };
  return $typemap_1->{ $name };
}

sub get_typemap {
    return $typemap_1;
}

1;

__END__

__END__

=pod

=head1 NAME

CiscoUC::RIS::10_5::Typemaps::RISService - typemap for RISService

=head1 DESCRIPTION

Typemap created by SOAP::WSDL for map-based SOAP message parsers.

=cut

