
package CiscoUC::RIS::10_5::Elements::executeCCMSQLStatement;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' }

__PACKAGE__->__set_name('executeCCMSQLStatement');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ExecuteSQLInputData_of :ATTR(:get<ExecuteSQLInputData>);
my %GetColumns_of :ATTR(:get<GetColumns>);

__PACKAGE__->_factory(
    [ qw(        ExecuteSQLInputData
        GetColumns

    ) ],
    {
        'ExecuteSQLInputData' => \%ExecuteSQLInputData_of,
        'GetColumns' => \%GetColumns_of,
    },
    {
        'ExecuteSQLInputData' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'GetColumns' => 'CiscoUC::RIS::10_5::Types::ColumnType',
    },
    {

        'ExecuteSQLInputData' => 'ExecuteSQLInputData',
        'GetColumns' => 'GetColumns',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CiscoUC::RIS::10_5::Elements::executeCCMSQLStatement

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
executeCCMSQLStatement from the namespace http://schemas.cisco.com/ast/soap.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ExecuteSQLInputData

 $element->set_ExecuteSQLInputData($data);
 $element->get_ExecuteSQLInputData();




=item * GetColumns

 $element->set_GetColumns($data);
 $element->get_GetColumns();





=back


=head1 METHODS

=head2 new

 my $element = CiscoUC::RIS::10_5::Elements::executeCCMSQLStatement->new($data);

Constructor. The following data structure may be passed to new():

 {
   ExecuteSQLInputData =>  $some_value, # string
   GetColumns =>  { # CiscoUC::RIS::10_5::Types::ColumnType
     ColumnName =>  $some_value, # string
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

