package ServiceabilityTools::10::0::Types::ProductServiceSpecification;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ServiceName_of :ATTR(:get<ServiceName>);
my %ServiceType_of :ATTR(:get<ServiceType>);
my %Deployable_of :ATTR(:get<Deployable>);
my %GroupName_of :ATTR(:get<GroupName>);
my %ProductID_of :ATTR(:get<ProductID>);
my %DependentServices_of :ATTR(:get<DependentServices>);

__PACKAGE__->_factory(
    [ qw(        ServiceName
        ServiceType
        Deployable
        GroupName
        ProductID
        DependentServices

    ) ],
    {
        'ServiceName' => \%ServiceName_of,
        'ServiceType' => \%ServiceType_of,
        'Deployable' => \%Deployable_of,
        'GroupName' => \%GroupName_of,
        'ProductID' => \%ProductID_of,
        'DependentServices' => \%DependentServices_of,
    },
    {
        'ServiceName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ServiceType' => 'ServiceabilityTools::10::0::Types::ServiceTypes',
        'Deployable' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
        'GroupName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ProductID' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'DependentServices' => 'ServiceabilityTools::10::0::Types::DependentServices',
    },
    {

        'ServiceName' => 'ServiceName',
        'ServiceType' => 'ServiceType',
        'Deployable' => 'Deployable',
        'GroupName' => 'GroupName',
        'ProductID' => 'ProductID',
        'DependentServices' => 'DependentServices',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

ServiceabilityTools::10::0::Types::ProductServiceSpecification

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ProductServiceSpecification from the namespace http://schemas.cisco.com/ast/soap.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ServiceName (min/maxOccurs: 1/1)


=item * ServiceType (min/maxOccurs: 1/1)


=item * Deployable (min/maxOccurs: 1/1)


=item * GroupName (min/maxOccurs: 1/1)


=item * ProductID (min/maxOccurs: 1/1)


=item * DependentServices (min/maxOccurs: 1/1)




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # ServiceabilityTools::10::0::Types::ProductServiceSpecification
   ServiceName =>  $some_value, # string
   ServiceType => $some_value, # ServiceTypes
   Deployable =>  $some_value, # boolean
   GroupName =>  $some_value, # string
   ProductID =>  $some_value, # string
   DependentServices =>  { # ServiceabilityTools::10::0::Types::DependentServices
     Service =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

