
package CiscoUC::RIS::10_0::Elements::selectCmDevice;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' }

__PACKAGE__->__set_name('selectCmDevice');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %StateInfo_of :ATTR(:get<StateInfo>);
my %CmSelectionCriteria_of :ATTR(:get<CmSelectionCriteria>);

__PACKAGE__->_factory(
    [ qw(        StateInfo
        CmSelectionCriteria

    ) ],
    {
        'StateInfo' => \%StateInfo_of,
        'CmSelectionCriteria' => \%CmSelectionCriteria_of,
    },
    {
        'StateInfo' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'CmSelectionCriteria' => 'CiscoUC::RIS::10_0::Types::CmSelectionCriteria',
    },
    {

        'StateInfo' => 'StateInfo',
        'CmSelectionCriteria' => 'CmSelectionCriteria',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CiscoUC::RIS::10_0::Elements::selectCmDevice

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
selectCmDevice from the namespace http://schemas.cisco.com/ast/soap.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * StateInfo

 $element->set_StateInfo($data);
 $element->get_StateInfo();




=item * CmSelectionCriteria

 $element->set_CmSelectionCriteria($data);
 $element->get_CmSelectionCriteria();





=back


=head1 METHODS

=head2 new

 my $element = CiscoUC::RIS::10_0::Elements::selectCmDevice->new($data);

Constructor. The following data structure may be passed to new():

 {
   StateInfo =>  $some_value, # string
   CmSelectionCriteria =>  { # CiscoUC::RIS::10_0::Types::CmSelectionCriteria
     MaxReturnedDevices =>  $some_value, # unsignedInt
     DeviceClass =>  $some_value, # string
     Model =>  $some_value, # unsignedInt
     Status =>  $some_value, # string
     NodeName =>  $some_value, # string
     SelectBy =>  $some_value, # string
     SelectItems =>  { # CiscoUC::RIS::10_0::Types::ArrayOfSelectItem
       item =>  { # CiscoUC::RIS::10_0::Types::SelectItem
         Item =>  $some_value, # string
       },
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

