package ServiceabilityTools::10::5::Types::InstalledProduct;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ProductName_of :ATTR(:get<ProductName>);
my %ProductVersion_of :ATTR(:get<ProductVersion>);
my %ProductDescription_of :ATTR(:get<ProductDescription>);
my %ProductID_of :ATTR(:get<ProductID>);
my %ShortName_of :ATTR(:get<ShortName>);

__PACKAGE__->_factory(
    [ qw(        ProductName
        ProductVersion
        ProductDescription
        ProductID
        ShortName

    ) ],
    {
        'ProductName' => \%ProductName_of,
        'ProductVersion' => \%ProductVersion_of,
        'ProductDescription' => \%ProductDescription_of,
        'ProductID' => \%ProductID_of,
        'ShortName' => \%ShortName_of,
    },
    {
        'ProductName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ProductVersion' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ProductDescription' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ProductID' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ShortName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'ProductName' => 'ProductName',
        'ProductVersion' => 'ProductVersion',
        'ProductDescription' => 'ProductDescription',
        'ProductID' => 'ProductID',
        'ShortName' => 'ShortName',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

ServiceabilityTools::10::5::Types::InstalledProduct

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
InstalledProduct from the namespace http://schemas.cisco.com/ast/soap.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ProductName (min/maxOccurs: 1/1)


=item * ProductVersion (min/maxOccurs: 1/1)


=item * ProductDescription (min/maxOccurs: 1/1)


=item * ProductID (min/maxOccurs: 1/1)


=item * ShortName (min/maxOccurs: 1/1)




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # ServiceabilityTools::10::5::Types::InstalledProduct
   ProductName =>  $some_value, # string
   ProductVersion =>  $some_value, # string
   ProductDescription =>  $some_value, # string
   ProductID =>  $some_value, # string
   ShortName =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

