
package CiscoUC::Serviceability::9_1::Elements::soapGetStaticServiceList;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' }

__PACKAGE__->__set_name('soapGetStaticServiceList');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ServiceInformationResponse_of :ATTR(:get<ServiceInformationResponse>);

__PACKAGE__->_factory(
    [ qw(        ServiceInformationResponse

    ) ],
    {
        'ServiceInformationResponse' => \%ServiceInformationResponse_of,
    },
    {
        'ServiceInformationResponse' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'ServiceInformationResponse' => 'ServiceInformationResponse',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CiscoUC::Serviceability::9_1::Elements::soapGetStaticServiceList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
soapGetStaticServiceList from the namespace http://schemas.cisco.com/ast/soap.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ServiceInformationResponse

 $element->set_ServiceInformationResponse($data);
 $element->get_ServiceInformationResponse();





=back


=head1 METHODS

=head2 new

 my $element = CiscoUC::Serviceability::9_1::Elements::soapGetStaticServiceList->new($data);

Constructor. The following data structure may be passed to new():

 {
   ServiceInformationResponse =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

