
package CiscoUC::Serviceability::9_1::Elements::soapGetServiceStatusResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' }

__PACKAGE__->__set_name('soapGetServiceStatusResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %soapGetServiceStatusReturn_of :ATTR(:get<soapGetServiceStatusReturn>);

__PACKAGE__->_factory(
    [ qw(        soapGetServiceStatusReturn

    ) ],
    {
        'soapGetServiceStatusReturn' => \%soapGetServiceStatusReturn_of,
    },
    {
        'soapGetServiceStatusReturn' => 'CiscoUC::Serviceability::9_1::Types::ServiceInformationResponse',
    },
    {

        'soapGetServiceStatusReturn' => 'soapGetServiceStatusReturn',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CiscoUC::Serviceability::9_1::Elements::soapGetServiceStatusResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
soapGetServiceStatusResponse from the namespace http://schemas.cisco.com/ast/soap.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * soapGetServiceStatusReturn

 $element->set_soapGetServiceStatusReturn($data);
 $element->get_soapGetServiceStatusReturn();





=back


=head1 METHODS

=head2 new

 my $element = CiscoUC::Serviceability::9_1::Elements::soapGetServiceStatusResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   soapGetServiceStatusReturn =>  { # CiscoUC::Serviceability::9_1::Types::ServiceInformationResponse
     ReturnCode =>  { value => $some_value },
     ReasonCode =>  $some_value, # integer
     ReasonString =>  $some_value, # string
     ServiceInfoList =>  { # CiscoUC::Serviceability::9_1::Types::ArrayOfServiceInformation
       item =>  { # CiscoUC::Serviceability::9_1::Types::ServiceInformation
         ServiceName =>  $some_value, # string
         ServiceStatus => $some_value, # ServiceStatus
         ReasonCode =>  $some_value, # integer
         ReasonCodeString =>  $some_value, # string
         StartTime =>  $some_value, # string
         UpTime =>  $some_value, # integer
       },
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

