package CiscoUC::Log::9_1::Types::NodeServiceLogList;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %name_of :ATTR(:get<name>);
my %ServiceLog_of :ATTR(:get<ServiceLog>);
my %SystemLog_of :ATTR(:get<SystemLog>);

__PACKAGE__->_factory(
    [ qw(        name
        ServiceLog
        SystemLog

    ) ],
    {
        'name' => \%name_of,
        'ServiceLog' => \%ServiceLog_of,
        'SystemLog' => \%SystemLog_of,
    },
    {
        'name' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ServiceLog' => 'CiscoUC::Log::9_1::Types::ArrayOfServiceLog',
        'SystemLog' => 'CiscoUC::Log::9_1::Types::ArrayOfSystemLog',
    },
    {

        'name' => 'name',
        'ServiceLog' => 'ServiceLog',
        'SystemLog' => 'SystemLog',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

CiscoUC::Log::9_1::Types::NodeServiceLogList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
NodeServiceLogList from the namespace http://schemas.cisco.com/ast/soap.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * name


=item * ServiceLog


=item * SystemLog




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CiscoUC::Log::9_1::Types::NodeServiceLogList
   name =>  $some_value, # string
   ServiceLog =>  { # CiscoUC::Log::9_1::Types::ArrayOfServiceLog
     item =>  $some_value, # string
   },
   SystemLog =>  { # CiscoUC::Log::9_1::Types::ArrayOfSystemLog
     item =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

