package CiscoUC::RIS::9_1::Types::CtiLine;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %DirNumber_of :ATTR(:get<DirNumber>);
my %LineStatus_of :ATTR(:get<LineStatus>);
my %LineStatusReason_of :ATTR(:get<LineStatusReason>);
my %LineTimeStamp_of :ATTR(:get<LineTimeStamp>);

__PACKAGE__->_factory(
    [ qw(        DirNumber
        LineStatus
        LineStatusReason
        LineTimeStamp

    ) ],
    {
        'DirNumber' => \%DirNumber_of,
        'LineStatus' => \%LineStatus_of,
        'LineStatusReason' => \%LineStatusReason_of,
        'LineTimeStamp' => \%LineTimeStamp_of,
    },
    {
        'DirNumber' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'LineStatus' => 'CiscoUC::RIS::9_1::Types::CtiStatus',
        'LineStatusReason' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
        'LineTimeStamp' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
    },
    {

        'DirNumber' => 'DirNumber',
        'LineStatus' => 'LineStatus',
        'LineStatusReason' => 'LineStatusReason',
        'LineTimeStamp' => 'LineTimeStamp',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

CiscoUC::RIS::9_1::Types::CtiLine

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
CtiLine from the namespace http://schemas.cisco.com/ast/soap.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * DirNumber


=item * LineStatus


=item * LineStatusReason


=item * LineTimeStamp




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CiscoUC::RIS::9_1::Types::CtiLine
   DirNumber =>  $some_value, # string
   LineStatus => $some_value, # CtiStatus
   LineStatusReason =>  $some_value, # unsignedInt
   LineTimeStamp =>  $some_value, # unsignedInt
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

