package CiscoUC::CDR::10_5::Interfaces::CDRonDemandService::CDRonDemand;
use strict;
use warnings;
use Class::Std::Fast::Storable;
use Scalar::Util qw(blessed);
use base qw(SOAP::WSDL::Client::Base);

# only load if it hasn't been loaded before
require CiscoUC::CDR::10_5::Typemaps::CDRonDemandService
    if not CiscoUC::CDR::10_5::Typemaps::CDRonDemandService->can('get_class');

sub START {
    $_[0]->set_proxy('https://192.168.1.47:8443/CDRonDemandService2/services/CDRonDemandService') if not $_[2]->{proxy};
    $_[0]->set_class_resolver('CiscoUC::CDR::10_5::Typemaps::CDRonDemandService')
        if not $_[2]->{class_resolver};

    $_[0]->set_prefix($_[2]->{use_prefix}) if exists $_[2]->{use_prefix};
}

sub get_file_list {
    my ($self, $body, $header) = @_;
    die "get_file_list must be called as object method (\$self is <$self>)" if not blessed($self);
    return $self->SUPER::call({
        operation => 'get_file_list',
        soap_action => 'get_file_list',
        style => 'document',
        body => {
            

           'use'            => 'literal',
            namespace       => 'http://schemas.xmlsoap.org/wsdl/soap/',
            encodingStyle   => '',
            parts           =>  [qw( CiscoUC::CDR::10_5::Elements::get_file_list )],
        },
        header => {
            
        },
        headerfault => {
            
        }
    }, $body, $header);
}


sub get_file {
    my ($self, $body, $header) = @_;
    die "get_file must be called as object method (\$self is <$self>)" if not blessed($self);
    return $self->SUPER::call({
        operation => 'get_file',
        soap_action => 'get_file',
        style => 'document',
        body => {
            

           'use'            => 'literal',
            namespace       => 'http://schemas.xmlsoap.org/wsdl/soap/',
            encodingStyle   => '',
            parts           =>  [qw( CiscoUC::CDR::10_5::Elements::get_file )],
        },
        header => {
            
        },
        headerfault => {
            
        }
    }, $body, $header);
}




1;



__END__

=pod

=head1 NAME

CiscoUC::CDR::10_5::Interfaces::CDRonDemandService::CDRonDemand - SOAP Interface for the CDRonDemandService Web Service

=head1 SYNOPSIS

 use CiscoUC::CDR::10_5::Interfaces::CDRonDemandService::CDRonDemand;
 my $interface = CiscoUC::CDR::10_5::Interfaces::CDRonDemandService::CDRonDemand->new();

 my $response;
 $response = $interface->get_file_list();
 $response = $interface->get_file();



=head1 DESCRIPTION

SOAP Interface for the CDRonDemandService web service
located at https://192.168.1.47:8443/CDRonDemandService2/services/CDRonDemandService.

=head1 SERVICE CDRonDemandService



=head2 Port CDRonDemand



=head1 METHODS

=head2 General methods

=head3 new

Constructor.

All arguments are forwarded to L<SOAP::WSDL::Client|SOAP::WSDL::Client>.

=head2 SOAP Service methods

Method synopsis is displayed with hash refs as parameters.

The commented class names in the method's parameters denote that objects
of the corresponding class can be passed instead of the marked hash ref.

You may pass any combination of objects, hash and list refs to these
methods, as long as you meet the structure.

List items (i.e. multiple occurences) are not displayed in the synopsis.
You may generally pass a list ref of hash refs (or objects) instead of a hash
ref - this may result in invalid XML if used improperly, though. Note that
SOAP::WSDL always expects list references at maximum depth position.

XML attributes are not displayed in this synopsis and cannot be set using
hash refs. See the respective class' documentation for additional information.



=head3 get_file_list



Returns a L<CiscoUC::CDR::10_5::Elements::get_file_listResponse|CiscoUC::CDR::10_5::Elements::get_file_listResponse> object.

 $response = $interface->get_file_list( {
    in0 =>  $some_value, # string
    in1 =>  $some_value, # string
    in2 =>  $some_value, # boolean
  },,
 );

=head3 get_file



Returns a L<CiscoUC::CDR::10_5::Elements::get_fileResponse|CiscoUC::CDR::10_5::Elements::get_fileResponse> object.

 $response = $interface->get_file( {
    in0 =>  $some_value, # string
    in1 =>  $some_value, # string
    in2 =>  $some_value, # string
    in3 =>  $some_value, # string
    in4 =>  $some_value, # string
    in5 =>  $some_value, # boolean
  },,
 );



=head1 AUTHOR

Generated by SOAP::WSDL on Sat Sep  6 22:24:47 2014

=cut
