package CiscoUC::Serviceability::10_0::Types::ServiceInformationResponse;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ReturnCode_of :ATTR(:get<ReturnCode>);
my %ReasonCode_of :ATTR(:get<ReasonCode>);
my %ReasonString_of :ATTR(:get<ReasonString>);
my %ServiceInfoList_of :ATTR(:get<ServiceInfoList>);

__PACKAGE__->_factory(
    [ qw(        ReturnCode
        ReasonCode
        ReasonString
        ServiceInfoList

    ) ],
    {
        'ReturnCode' => \%ReturnCode_of,
        'ReasonCode' => \%ReasonCode_of,
        'ReasonString' => \%ReasonString_of,
        'ServiceInfoList' => \%ServiceInfoList_of,
    },
    {
        'ReturnCode' => 'CiscoUC::Serviceability::10_0::Types::ReturnCode',
        'ReasonCode' => 'SOAP::WSDL::XSD::Typelib::Builtin::integer',
        'ReasonString' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ServiceInfoList' => 'CiscoUC::Serviceability::10_0::Types::ArrayOfServiceInformation',
    },
    {

        'ReturnCode' => 'ReturnCode',
        'ReasonCode' => 'ReasonCode',
        'ReasonString' => 'ReasonString',
        'ServiceInfoList' => 'ServiceInfoList',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

CiscoUC::Serviceability::10_0::Types::ServiceInformationResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ServiceInformationResponse from the namespace http://schemas.cisco.com/ast/soap.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ReturnCode


=item * ReasonCode


=item * ReasonString


=item * ServiceInfoList




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CiscoUC::Serviceability::10_0::Types::ServiceInformationResponse
   ReturnCode =>  { value => $some_value },
   ReasonCode =>  $some_value, # integer
   ReasonString =>  $some_value, # string
   ServiceInfoList =>  { # CiscoUC::Serviceability::10_0::Types::ArrayOfServiceInformation
     item =>  { # CiscoUC::Serviceability::10_0::Types::ServiceInformation
       ServiceName =>  $some_value, # string
       ServiceStatus => $some_value, # ServiceStatus
       ReasonCode =>  $some_value, # integer
       ReasonCodeString =>  $some_value, # string
       StartTime =>  $some_value, # string
       UpTime =>  $some_value, # integer
     },
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

