
package CiscoUC::Serviceability::10_0::Elements::getProductInformationList;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' }

__PACKAGE__->__set_name('getProductInformationList');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ServiceInfo_of :ATTR(:get<ServiceInfo>);

__PACKAGE__->_factory(
    [ qw(        ServiceInfo

    ) ],
    {
        'ServiceInfo' => \%ServiceInfo_of,
    },
    {
        'ServiceInfo' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'ServiceInfo' => 'ServiceInfo',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CiscoUC::Serviceability::10_0::Elements::getProductInformationList

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
getProductInformationList from the namespace http://schemas.cisco.com/ast/soap.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ServiceInfo

 $element->set_ServiceInfo($data);
 $element->get_ServiceInfo();





=back


=head1 METHODS

=head2 new

 my $element = CiscoUC::Serviceability::10_0::Elements::getProductInformationList->new($data);

Constructor. The following data structure may be passed to new():

 {
   ServiceInfo =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

