
package CiscoUC::Serviceability::10_0::Elements::soapDoServiceDeployment;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' }

__PACKAGE__->__set_name('soapDoServiceDeployment');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %DeploymentServiceRequest_of :ATTR(:get<DeploymentServiceRequest>);

__PACKAGE__->_factory(
    [ qw(        DeploymentServiceRequest

    ) ],
    {
        'DeploymentServiceRequest' => \%DeploymentServiceRequest_of,
    },
    {
        'DeploymentServiceRequest' => 'CiscoUC::Serviceability::10_0::Types::DeploymentServiceRequest',
    },
    {

        'DeploymentServiceRequest' => 'DeploymentServiceRequest',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CiscoUC::Serviceability::10_0::Elements::soapDoServiceDeployment

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
soapDoServiceDeployment from the namespace http://schemas.cisco.com/ast/soap.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * DeploymentServiceRequest

 $element->set_DeploymentServiceRequest($data);
 $element->get_DeploymentServiceRequest();





=back


=head1 METHODS

=head2 new

 my $element = CiscoUC::Serviceability::10_0::Elements::soapDoServiceDeployment->new($data);

Constructor. The following data structure may be passed to new():

 {
   DeploymentServiceRequest =>  { # CiscoUC::Serviceability::10_0::Types::DeploymentServiceRequest
     NodeName =>  $some_value, # string
     DeployType => $some_value, # DeployType
     ServiceList =>  { # CiscoUC::Serviceability::10_0::Types::ArrayOfServices
       item =>  $some_value, # string
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

