package CiscoUC::RIS::10_5::Types::selectCtiItemReturn;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %SelectCtiItemResult_of :ATTR(:get<SelectCtiItemResult>);
my %StateInfo_of :ATTR(:get<StateInfo>);

__PACKAGE__->_factory(
    [ qw(        SelectCtiItemResult
        StateInfo

    ) ],
    {
        'SelectCtiItemResult' => \%SelectCtiItemResult_of,
        'StateInfo' => \%StateInfo_of,
    },
    {
        'SelectCtiItemResult' => 'CiscoUC::RIS::10_5::Types::SelectCtiItemResult',
        'StateInfo' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'SelectCtiItemResult' => 'SelectCtiItemResult',
        'StateInfo' => 'StateInfo',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

CiscoUC::RIS::10_5::Types::selectCtiItemReturn

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
selectCtiItemReturn from the namespace http://schemas.cisco.com/ast/soap.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * SelectCtiItemResult


=item * StateInfo




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CiscoUC::RIS::10_5::Types::selectCtiItemReturn
   SelectCtiItemResult =>  { # CiscoUC::RIS::10_5::Types::SelectCtiItemResult
     TotalItemsFound =>  $some_value, # unsignedInt
     CtiNodes =>  { # CiscoUC::RIS::10_5::Types::ArrayOfCtiNode
       CtiNodes =>  { # CiscoUC::RIS::10_5::Types::CtiNode
         ReturnCode => $some_value, # RisReturnCode
         Name =>  $some_value, # string
         NoChange =>  $some_value, # boolean
         CtiItems =>  { # CiscoUC::RIS::10_5::Types::ArrayOfCtiItem
           CtiItems =>  { # CiscoUC::RIS::10_5::Types::CtiItem
             AppId =>  $some_value, # string
             UserId =>  $some_value, # string
             AppIpAddr =>  $some_value, # string
             AppStatus => $some_value, # CtiStatus
             AppStatusReason =>  $some_value, # unsignedInt
             AppTimeStamp =>  $some_value, # unsignedInt
             CtiDevice =>  { # CiscoUC::RIS::10_5::Types::CtiDevice
               AppControlsMedia =>  $some_value, # boolean
               DeviceName =>  $some_value, # string
               DeviceStatus => $some_value, # CtiStatus
               DeviceStatusReason =>  $some_value, # unsignedInt
               DeviceTimeStamp =>  $some_value, # unsignedInt
             },
             CtiLine =>  { # CiscoUC::RIS::10_5::Types::CtiLine
               DirNumber =>  $some_value, # string
               LineStatus => $some_value, # CtiStatus
               LineStatusReason =>  $some_value, # unsignedInt
               LineTimeStamp =>  $some_value, # unsignedInt
             },
           },
         },
       },
     },
   },
   StateInfo =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

