package CiscoUC::RIS::10_0::Types::ArrayOfSelectDevName;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %SelectDevName_of :ATTR(:get<SelectDevName>);

__PACKAGE__->_factory(
    [ qw(        SelectDevName

    ) ],
    {
        'SelectDevName' => \%SelectDevName_of,
    },
    {
        'SelectDevName' => 'CiscoUC::RIS::10_0::Types::SelectDevName',
    },
    {

        'SelectDevName' => 'SelectDevName',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

CiscoUC::RIS::10_0::Types::ArrayOfSelectDevName

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ArrayOfSelectDevName from the namespace http://schemas.cisco.com/ast/soap.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * SelectDevName




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CiscoUC::RIS::10_0::Types::ArrayOfSelectDevName
   SelectDevName =>  { # CiscoUC::RIS::10_0::Types::SelectDevName
     DevName =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

