package CiscoUC::RIS::10_0::Types::CmSelectionCriteria;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %MaxReturnedDevices_of :ATTR(:get<MaxReturnedDevices>);
my %DeviceClass_of :ATTR(:get<DeviceClass>);
my %Model_of :ATTR(:get<Model>);
my %Status_of :ATTR(:get<Status>);
my %NodeName_of :ATTR(:get<NodeName>);
my %SelectBy_of :ATTR(:get<SelectBy>);
my %SelectItems_of :ATTR(:get<SelectItems>);

__PACKAGE__->_factory(
    [ qw(        MaxReturnedDevices
        DeviceClass
        Model
        Status
        NodeName
        SelectBy
        SelectItems

    ) ],
    {
        'MaxReturnedDevices' => \%MaxReturnedDevices_of,
        'DeviceClass' => \%DeviceClass_of,
        'Model' => \%Model_of,
        'Status' => \%Status_of,
        'NodeName' => \%NodeName_of,
        'SelectBy' => \%SelectBy_of,
        'SelectItems' => \%SelectItems_of,
    },
    {
        'MaxReturnedDevices' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
        'DeviceClass' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'Model' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
        'Status' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'NodeName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'SelectBy' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'SelectItems' => 'CiscoUC::RIS::10_0::Types::ArrayOfSelectItem',
    },
    {

        'MaxReturnedDevices' => 'MaxReturnedDevices',
        'DeviceClass' => 'DeviceClass',
        'Model' => 'Model',
        'Status' => 'Status',
        'NodeName' => 'NodeName',
        'SelectBy' => 'SelectBy',
        'SelectItems' => 'SelectItems',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

CiscoUC::RIS::10_0::Types::CmSelectionCriteria

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
CmSelectionCriteria from the namespace http://schemas.cisco.com/ast/soap.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * MaxReturnedDevices


=item * DeviceClass


=item * Model


=item * Status


=item * NodeName


=item * SelectBy


=item * SelectItems




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CiscoUC::RIS::10_0::Types::CmSelectionCriteria
   MaxReturnedDevices =>  $some_value, # unsignedInt
   DeviceClass =>  $some_value, # string
   Model =>  $some_value, # unsignedInt
   Status =>  $some_value, # string
   NodeName =>  $some_value, # string
   SelectBy =>  $some_value, # string
   SelectItems =>  { # CiscoUC::RIS::10_0::Types::ArrayOfSelectItem
     item =>  { # CiscoUC::RIS::10_0::Types::SelectItem
       Item =>  $some_value, # string
     },
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

