package CiscoUC::RIS::10_0::Types::CtiNode;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ReturnCode_of :ATTR(:get<ReturnCode>);
my %Name_of :ATTR(:get<Name>);
my %NoChange_of :ATTR(:get<NoChange>);
my %CtiItems_of :ATTR(:get<CtiItems>);

__PACKAGE__->_factory(
    [ qw(        ReturnCode
        Name
        NoChange
        CtiItems

    ) ],
    {
        'ReturnCode' => \%ReturnCode_of,
        'Name' => \%Name_of,
        'NoChange' => \%NoChange_of,
        'CtiItems' => \%CtiItems_of,
    },
    {
        'ReturnCode' => 'CiscoUC::RIS::10_0::Types::RisReturnCode',
        'Name' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'NoChange' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
        'CtiItems' => 'CiscoUC::RIS::10_0::Types::ArrayOfCtiItem',
    },
    {

        'ReturnCode' => 'ReturnCode',
        'Name' => 'Name',
        'NoChange' => 'NoChange',
        'CtiItems' => 'CtiItems',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

CiscoUC::RIS::10_0::Types::CtiNode

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
CtiNode from the namespace http://schemas.cisco.com/ast/soap.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ReturnCode


=item * Name


=item * NoChange


=item * CtiItems




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CiscoUC::RIS::10_0::Types::CtiNode
   ReturnCode => $some_value, # RisReturnCode
   Name =>  $some_value, # string
   NoChange =>  $some_value, # boolean
   CtiItems =>  { # CiscoUC::RIS::10_0::Types::ArrayOfCtiItem
     CtiItems =>  { # CiscoUC::RIS::10_0::Types::CtiItem
       AppId =>  $some_value, # string
       UserId =>  $some_value, # string
       AppIpAddr =>  $some_value, # string
       AppStatus => $some_value, # CtiStatus
       AppStatusReason =>  $some_value, # unsignedInt
       AppTimeStamp =>  $some_value, # unsignedInt
       CtiDevice =>  { # CiscoUC::RIS::10_0::Types::CtiDevice
         AppControlsMedia =>  $some_value, # boolean
         DeviceName =>  $some_value, # string
         DeviceStatus => $some_value, # CtiStatus
         DeviceStatusReason =>  $some_value, # unsignedInt
         DeviceTimeStamp =>  $some_value, # unsignedInt
       },
       CtiLine =>  { # CiscoUC::RIS::10_0::Types::CtiLine
         DirNumber =>  $some_value, # string
         LineStatus => $some_value, # CtiStatus
         LineStatusReason =>  $some_value, # unsignedInt
         LineTimeStamp =>  $some_value, # unsignedInt
       },
     },
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

