package CiscoUC::RIS::10_0::Types::CtiSelectionCriteria;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %MaxReturnedItems_of :ATTR(:get<MaxReturnedItems>);
my %CtiMgrClass_of :ATTR(:get<CtiMgrClass>);
my %Status_of :ATTR(:get<Status>);
my %NodeName_of :ATTR(:get<NodeName>);
my %SelectAppBy_of :ATTR(:get<SelectAppBy>);
my %AppItems_of :ATTR(:get<AppItems>);
my %DevNames_of :ATTR(:get<DevNames>);
my %DirNumbers_of :ATTR(:get<DirNumbers>);

__PACKAGE__->_factory(
    [ qw(        MaxReturnedItems
        CtiMgrClass
        Status
        NodeName
        SelectAppBy
        AppItems
        DevNames
        DirNumbers

    ) ],
    {
        'MaxReturnedItems' => \%MaxReturnedItems_of,
        'CtiMgrClass' => \%CtiMgrClass_of,
        'Status' => \%Status_of,
        'NodeName' => \%NodeName_of,
        'SelectAppBy' => \%SelectAppBy_of,
        'AppItems' => \%AppItems_of,
        'DevNames' => \%DevNames_of,
        'DirNumbers' => \%DirNumbers_of,
    },
    {
        'MaxReturnedItems' => 'SOAP::WSDL::XSD::Typelib::Builtin::unsignedInt',
        'CtiMgrClass' => 'CiscoUC::RIS::10_0::Types::CtiMgrClass',
        'Status' => 'CiscoUC::RIS::10_0::Types::CtiStatus',
        'NodeName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'SelectAppBy' => 'CiscoUC::RIS::10_0::Types::CtiSelectAppBy',
        'AppItems' => 'CiscoUC::RIS::10_0::Types::ArrayOfSelectAppItem',
        'DevNames' => 'CiscoUC::RIS::10_0::Types::ArrayOfSelectDevName',
        'DirNumbers' => 'CiscoUC::RIS::10_0::Types::ArrayOfSelectDirNumber',
    },
    {

        'MaxReturnedItems' => 'MaxReturnedItems',
        'CtiMgrClass' => 'CtiMgrClass',
        'Status' => 'Status',
        'NodeName' => 'NodeName',
        'SelectAppBy' => 'SelectAppBy',
        'AppItems' => 'AppItems',
        'DevNames' => 'DevNames',
        'DirNumbers' => 'DirNumbers',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

CiscoUC::RIS::10_0::Types::CtiSelectionCriteria

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
CtiSelectionCriteria from the namespace http://schemas.cisco.com/ast/soap.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * MaxReturnedItems


=item * CtiMgrClass


=item * Status


=item * NodeName


=item * SelectAppBy


=item * AppItems


=item * DevNames


=item * DirNumbers




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CiscoUC::RIS::10_0::Types::CtiSelectionCriteria
   MaxReturnedItems =>  $some_value, # unsignedInt
   CtiMgrClass => $some_value, # CtiMgrClass
   Status => $some_value, # CtiStatus
   NodeName =>  $some_value, # string
   SelectAppBy => $some_value, # CtiSelectAppBy
   AppItems =>  { # CiscoUC::RIS::10_0::Types::ArrayOfSelectAppItem
     SelectAppItem =>  { # CiscoUC::RIS::10_0::Types::SelectAppItem
       AppItem =>  $some_value, # string
     },
   },
   DevNames =>  { # CiscoUC::RIS::10_0::Types::ArrayOfSelectDevName
     SelectDevName =>  { # CiscoUC::RIS::10_0::Types::SelectDevName
       DevName =>  $some_value, # string
     },
   },
   DirNumbers =>  { # CiscoUC::RIS::10_0::Types::ArrayOfSelectDirNumber
     item =>  { # CiscoUC::RIS::10_0::Types::SelectDirNumber
       DirNumber =>  $some_value, # string
     },
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

