
package CiscoUC::RIS::9_1::Elements::getServerInfoResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' }

__PACKAGE__->__set_name('getServerInfoResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ServerInformation_of :ATTR(:get<ServerInformation>);

__PACKAGE__->_factory(
    [ qw(        ServerInformation

    ) ],
    {
        'ServerInformation' => \%ServerInformation_of,
    },
    {
        'ServerInformation' => 'CiscoUC::RIS::9_1::Types::ServerInformation',
    },
    {

        'ServerInformation' => 'ServerInformation',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CiscoUC::RIS::9_1::Elements::getServerInfoResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
getServerInfoResponse from the namespace http://schemas.cisco.com/ast/soap.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ServerInformation

 $element->set_ServerInformation($data);
 $element->get_ServerInformation();





=back


=head1 METHODS

=head2 new

 my $element = CiscoUC::RIS::9_1::Elements::getServerInfoResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   ServerInformation =>  { # CiscoUC::RIS::9_1::Types::ServerInformation
     HostName =>  $some_value, # string
     os_name =>  $some_value, # string
     os_version =>  $some_value, # string
     os_arch =>  $some_value, # string
     java_runtime_version =>  $some_value, # string
     java_vm_vendor =>  $some_value, # string
     call_manager_version =>  $some_value, # string
     Active_Versions =>  $some_value, # string
     In_Active_Versions =>  $some_value, # string
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

