
package CiscoUC::RIS::9_1::Elements::selectCmDeviceSIPResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' }

__PACKAGE__->__set_name('selectCmDeviceSIPResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %selectCmDeviceSIPResponse_of :ATTR(:get<selectCmDeviceSIPResponse>);

__PACKAGE__->_factory(
    [ qw(        selectCmDeviceSIPResponse

    ) ],
    {
        'selectCmDeviceSIPResponse' => \%selectCmDeviceSIPResponse_of,
    },
    {
        'selectCmDeviceSIPResponse' => 'CiscoUC::RIS::9_1::Types::selectCmDeviceSIPReturn',
    },
    {

        'selectCmDeviceSIPResponse' => 'selectCmDeviceSIPResponse',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CiscoUC::RIS::9_1::Elements::selectCmDeviceSIPResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
selectCmDeviceSIPResponse from the namespace http://schemas.cisco.com/ast/soap.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * selectCmDeviceSIPResponse

 $element->set_selectCmDeviceSIPResponse($data);
 $element->get_selectCmDeviceSIPResponse();





=back


=head1 METHODS

=head2 new

 my $element = CiscoUC::RIS::9_1::Elements::selectCmDeviceSIPResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   selectCmDeviceSIPResponse =>  { # CiscoUC::RIS::9_1::Types::selectCmDeviceSIPReturn
     SelectCmDeviceResultSIP =>  { # CiscoUC::RIS::9_1::Types::SelectCmDeviceResultSIP
       TotalDevicesFound =>  $some_value, # unsignedInt
       CmNodes =>  { # CiscoUC::RIS::9_1::Types::ArrayOfCmNodeSIP
         CmNodeSIP =>  { # CiscoUC::RIS::9_1::Types::CmNodeSIP
           ReturnCode => $some_value, # RisReturnCode
           Name =>  $some_value, # string
           NoChange =>  $some_value, # boolean
           CmDevices =>  { # CiscoUC::RIS::9_1::Types::ArrayOfCmDeviceSIP
             item =>  { # CiscoUC::RIS::9_1::Types::CmDeviceSIP
               Name =>  $some_value, # string
               IpAddress =>  $some_value, # string
               DirNumber =>  $some_value, # string
               DeviceClass => $some_value, # DeviceClass
               Model =>  $some_value, # unsignedInt
               Product =>  $some_value, # unsignedInt
               BoxProduct =>  $some_value, # unsignedInt
               Httpd => $some_value, # CmDevHttpd
               RegistrationAttempts =>  $some_value, # unsignedInt
               IsCtiControllable =>  $some_value, # boolean
               LoginUserId =>  $some_value, # string
               Status => $some_value, # CmDevRegStat
               StatusReason =>  $some_value, # unsignedInt
               PerfMonObject =>  $some_value, # unsignedInt
               DChannel =>  $some_value, # unsignedInt
               Description =>  $some_value, # string
               H323Trunk =>  { # CiscoUC::RIS::9_1::Types::H323Trunk
                 ConfigName =>  $some_value, # string
                 TechPrefix =>  $some_value, # string
                 Zone =>  $some_value, # string
                 RemoteCmServer1 =>  $some_value, # string
                 RemoteCmServer2 =>  $some_value, # string
                 RemoteCmServer3 =>  $some_value, # string
                 AltGkList =>  $some_value, # string
                 ActiveGk =>  $some_value, # string
                 CallSignalAddr =>  $some_value, # string
                 RasAddr =>  $some_value, # string
               },
               TimeStamp =>  $some_value, # unsignedInt
               Protocol => $some_value, # ProtocolType
               NumOfLines =>  $some_value, # unsignedInt
               LinesStatus =>  { # CiscoUC::RIS::9_1::Types::ArrayOfCmDevSingleLineStatus
                 item =>  { # CiscoUC::RIS::9_1::Types::CmDevSingleLineStatus
                   DirectoryNumber =>  $some_value, # string
                   Status => $some_value, # CmSingleLineStatus
                 },
               },
             },
           },
         },
       },
     },
     StateInfo =>  $some_value, # string
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

