
package ServiceabilityTools::10::0::Elements::soapDoControlServices;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' }

__PACKAGE__->__set_name('soapDoControlServices');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ControlServiceRequest_of :ATTR(:get<ControlServiceRequest>);

__PACKAGE__->_factory(
    [ qw(        ControlServiceRequest

    ) ],
    {
        'ControlServiceRequest' => \%ControlServiceRequest_of,
    },
    {
        'ControlServiceRequest' => 'ServiceabilityTools::10::0::Types::ControlServiceRequest',
    },
    {

        'ControlServiceRequest' => 'ControlServiceRequest',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

ServiceabilityTools::10::0::Elements::soapDoControlServices

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
soapDoControlServices from the namespace http://schemas.cisco.com/ast/soap.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ControlServiceRequest

 $element->set_ControlServiceRequest($data);
 $element->get_ControlServiceRequest();





=back


=head1 METHODS

=head2 new

 my $element = ServiceabilityTools::10::0::Elements::soapDoControlServices->new($data);

Constructor. The following data structure may be passed to new():

 {
   ControlServiceRequest =>  { # ServiceabilityTools::10::0::Types::ControlServiceRequest
     NodeName =>  $some_value, # string
     ControlType => $some_value, # ControlType
     ServiceList =>  { # ServiceabilityTools::10::0::Types::ArrayOfServices
       item =>  $some_value, # string
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

