package CiscoUC::Log::10_0::Types::ResultSet;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %SchemaFileSelectionResult_of :ATTR(:get<SchemaFileSelectionResult>);

__PACKAGE__->_factory(
    [ qw(        SchemaFileSelectionResult

    ) ],
    {
        'SchemaFileSelectionResult' => \%SchemaFileSelectionResult_of,
    },
    {
        'SchemaFileSelectionResult' => 'CiscoUC::Log::10_0::Types::SchemaFileSelectionResult',
    },
    {

        'SchemaFileSelectionResult' => 'SchemaFileSelectionResult',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

CiscoUC::Log::10_0::Types::ResultSet

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ResultSet from the namespace http://schemas.cisco.com/ast/soap.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * SchemaFileSelectionResult




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CiscoUC::Log::10_0::Types::ResultSet
   SchemaFileSelectionResult =>  { # CiscoUC::Log::10_0::Types::SchemaFileSelectionResult
     Node =>  { # CiscoUC::Log::10_0::Types::Node
       name =>  $some_value, # string
       ServiceList =>  { # CiscoUC::Log::10_0::Types::ArrayOfServiceLogs
         ServiceLogs =>  { # CiscoUC::Log::10_0::Types::ServiceLogs
           name =>  $some_value, # string
           SetOfFiles =>  { # CiscoUC::Log::10_0::Types::ArrayOfFile
             File =>  { # CiscoUC::Log::10_0::Types::File
               name =>  $some_value, # string
               absolutepath =>  $some_value, # string
               filesize =>  $some_value, # string
               modifiedDate =>  $some_value, # string
             },
           },
         },
       },
     },
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

