package CiscoUC::CDR::9_1::Types::ArrayOfFileName;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %FileName_of :ATTR(:get<FileName>);

__PACKAGE__->_factory(
    [ qw(        FileName

    ) ],
    {
        'FileName' => \%FileName_of,
    },
    {
        'FileName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'FileName' => 'FileName',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

CiscoUC::CDR::9_1::Types::ArrayOfFileName

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ArrayOfFileName from the namespace http://schemas.cisco.com/ast/soap.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * FileName




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CiscoUC::CDR::9_1::Types::ArrayOfFileName
   FileName =>  $some_value, # string
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

