
package CiscoUC::Log::9_1::Elements::selectLogFiles;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://schemas.cisco.com/ast/soap' }

__PACKAGE__->__set_name('selectLogFiles');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %FileSelectionCriteria_of :ATTR(:get<FileSelectionCriteria>);

__PACKAGE__->_factory(
    [ qw(        FileSelectionCriteria

    ) ],
    {
        'FileSelectionCriteria' => \%FileSelectionCriteria_of,
    },
    {
        'FileSelectionCriteria' => 'CiscoUC::Log::9_1::Types::SchemaFileSelectionCriteria',
    },
    {

        'FileSelectionCriteria' => 'FileSelectionCriteria',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CiscoUC::Log::9_1::Elements::selectLogFiles

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
selectLogFiles from the namespace http://schemas.cisco.com/ast/soap.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * FileSelectionCriteria

 $element->set_FileSelectionCriteria($data);
 $element->get_FileSelectionCriteria();





=back


=head1 METHODS

=head2 new

 my $element = CiscoUC::Log::9_1::Elements::selectLogFiles->new($data);

Constructor. The following data structure may be passed to new():

 {
   FileSelectionCriteria =>  { # CiscoUC::Log::9_1::Types::SchemaFileSelectionCriteria
     ServiceLogs =>  { # CiscoUC::Log::9_1::Types::ArrayOfServiceLog
       item =>  $some_value, # string
     },
     SystemLogs =>  { # CiscoUC::Log::9_1::Types::ArrayOfSystemLog
       item =>  $some_value, # string
     },
     SearchStr =>  $some_value, # string
     Frequency => $some_value, # Frequency
     JobType => $some_value, # JobType
     ToDate =>  $some_value, # string
     FromDate =>  $some_value, # string
     TimeZone =>  $some_value, # string
     RelText => $some_value, # RelText
     RelTime =>  $some_value, # byte
     Port =>  $some_value, # byte
     IPAddress =>  $some_value, # string
     UserName =>  $some_value, # string
     Password =>  $some_value, # string
     ZipInfo =>  $some_value, # boolean
     RemoteFolder =>  $some_value, # string
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

